- name: Install Docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - jq
      - python-pip
    update_cache: true
    autoremove: true
  when: not running and not custom_image

- name: Install required Python dependencies
  pip:
    name: docker
    state: latest
  when: not running and not custom_image

- name: Add Docker CE official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: not running and not custom_image

- name: Add Docker CE repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
  when: not running and not custom_image

- name: Install Docker CE
  apt:
    name: docker-ce
    update_cache: true
  when: not running and not custom_image

- name: Add sudo user to "docker" group
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: true
  when: not running and not custom_image
