- hosts: "{{ fs }}"
  gather_facts: false
  become: true
  tasks:
    - name: Find attached block devices
      shell: >
        lsblk -J | jq '.blockdevices[]
        | select(.type == "disk")
        | select(.name != "sda")
        | .name' | sed 's/"//g'
      register: block_devices

    - name: Make XFS on the 1st block device
      filesystem:
        fstype: xfs
        dev: /dev/{{ block_devices.stdout_lines[0] }}

    - name: Create {{ options.ganesha.mountpoint }}
      file:
        path: "{{ options.ganesha.mountpoint }}"
        state: directory
        recurse: true
        mode: 0777

    - name: Mount the filesystem to {{ options.ganesha.mountpoint }}
      mount:
        path: "{{ options.ganesha.mountpoint }}"
        src: /dev/{{ block_devices.stdout_lines[0] }}
        fstype: xfs
        state: mounted

    - name: Run NFS Ganesha
      docker_container:
        name: nfs-ganesha
        image: "{{ options.ganesha.docker_image }}"
        network_mode: host
        privileged: true
        pull: true
        volumes:
          - "{{ options.ganesha.mountpoint }}:/data/nfs"
