- name: Fetch measurement files
  fetch:
    src: "/data/stats-{{ inventory_hostname }}-{{ item }}.txt"
    dest: ./data/{{ hostvars.localhost.benchmark_id }}
    flat: true
  with_sequence: start=1 end={{ client.n_parallel }}