- hosts: localhost
  gather_facts: false
  tasks:
    - name: Select the first host as the GlusterFS admin host
      add_host:
        hostname: "{{ groups[fs].0 }}"
        groupname: glusterfs-admin

- hosts: "{{ fs }}"
  become: true
  tasks:
    - name: Add GlusterFS repo
      apt_repository:
        repo: ppa:gluster/glusterfs-{{ options.glusterfs.version }}

    - name: Install GlusterFS server
      apt:
        name: glusterfs-server
        update_cache: true

    - name: Start GlusterFS
      systemd:
        name: glusterd
        state: started
        enabled: true

    - name: Find attached block devices
      shell: >
        lsblk -J | jq '.blockdevices[]
        | select(.type == "disk")
        | select(.name != "sda")
        | .name' | sed 's/"//g'
      register: block_devices

    - name: Create mountpoints for the block devices
      file:
        path: /brick/{{ item }}
        state: directory
      with_items: "{{ block_devices.stdout_lines }}"

    - name: Make XFS on the block devices
      filesystem:
        fstype: xfs
        dev: /dev/{{ item }}
      with_items: "{{ block_devices.stdout_lines }}"

    - name: Mount the block devices
      mount:
        path: /brick/{{ item }}"
        src: /dev/{{ item }}
        fstype: xfs
        state: mounted
      with_items: "{{ block_devices.stdout_lines }}"

- hosts: glusterfs-admin
  gather_facts: false
  become: true
  tasks:
    - name: Peer up with other GlusterFS nodes
      shell: >
        gluster peer probe {{ hostvars[item].ansible_default_ipv4.address }}
      with_items: "{{ groups[fs][1:] }}"

    - name: Collect all bricks
      set_fact:
        bricks: >
          {{
            (bricks|default([]))
            + ["%s:/brick/%s/%s"|format(hostvars[item.0].ansible_default_ipv4.address,
                                        item.1,
                                        options.glusterfs.name)]
          }}
      with_nested:
        - "{{ groups[fs] }}"
        - "{{ block_devices.stdout_lines }}"

    - name: Create the volume over all the bricks
      shell: >
        gluster volume create {{ options.glusterfs.name }}
        replica {{ options.glusterfs.replication_factor }}
        transport {{ options.glusterfs.transport_mode }}
        {{ bricks | join(' ') }} force

    - name: Start the volume
      shell: >
        gluster volume start {{ options.glusterfs.name }}










