ansible_ssh_user: centos
ansible_ssh_public_key_file: ~/.ssh/id_rsa.pub
ansible_ssh_private_key_file: ~/.ssh/id_rsa

project: helium-dc
image: ubuntu-1804
max_retries: 5
supernet: 10.52.0.0/16

mode: server
machine_type: n1-standard-2
preemptible: false
options:
  ceph_daemon_image: ceph/daemon:latest-luminous
  ceph_mon_group_size: 1
  cephfs_group_size: 1
  cephfs_name: alpha

disks:
  - name: boot
    type: pd-ssd
    size: 30
    delete_on_termination: true
    mode: READ_WRITE
  - name: ext-0
    type: pd-ssd
    size: 10
    delete_on_termination: true
    mode: READ_WRITE
zone:
  - name: us-east1-b
    start: 1
    end: 4
#  - name: us-east4
#    count: 2
#  - name: us-central1
#    count: 3
#  - name: us-west1
#    count: 4
#  - name: northamerica-northeast1
#    count: 5


