ansible_ssh_private_key_file: ~/.ssh/id_rsa
ansible_ssh_public_key_file: ~/.ssh/id_rsa.pub
ansible_ssh_user: centos
client:
  dir: /
  host: 10.52.100.9
  n_parallel: 1
  opts: vers=4
  type: nfs
disks:
- delete_on_termination: true
  mode: READ_WRITE
  name: boot
  size: 30
  type: pd-ssd
- delete_on_termination: true
  mode: READ_WRITE
  name: ext-0
  size: 100
  type: pd-ssd
image: ubuntu-1804
machine_type: n1-standard-16
max_retries: 5
mode: server
options:
  cephfs:
    daemon_image: ceph/daemon:latest-luminous
    mds_group_size: 1
    mon_group_size: 1
    name: alpha
  ganesha:
    docker_image: janeczku/nfs-ganesha
    mountpoint: /data
  gfganesha:
    name: alpha
    replication_factor: 3
    transport_mode: tcp
    version: 4.0
  glusterfs:
    name: alpha
    replication_factor: 3
    transport_mode: tcp
    version: 4.0
  iozone:
    docker_image: dchampion24/iozone:nfs
    opts: -Rac -r 4k -s 512m
  nfsv4:
    mountpoint: /data
    nfsd_image: heliumdatacommons/nfsd
    opts: rw,fsid=0,insecure,no_subtree_check,anonuid=1000,anongid=1000,no_root_squash
  rbd:
    daemon_image: ceph/daemon:latest-luminous
    mon_group_size: 1
    mountpoint: /data
    name: alpha
    nfsd_image: heliumdatacommons/nfsd
    num_pgs: 8
    opts: rw,fsid=0,insecure,no_subtree_check,anonuid=1000,anongid=1000,no_root_squash
    unwanted_rbd_features: exclusive-lock object-map fast-diff deep-flatten
  rbdganesha:
    daemon_image: ceph/daemon:latest-luminous
    ganesha_image: janeczku/nfs-ganesha
    mon_group_size: 1
    mountpoint: /data
    name: alpha
    num_pgs: 8
    unwanted_rbd_features: exclusive-lock object-map fast-diff deep-flatten
preemptible: false
project: helium-dc
running: true
supernet: 10.52.0.0/16
zone:
- end: 1
  name: us-east1-b
  start: 1
