ansible_ssh_user: centos
ansible_ssh_public_key_file: ~/.ssh/id_rsa.pub
ansible_ssh_private_key_file: ~/.ssh/id_rsa

project: helium-dc
image: ubuntu-1804
machine_type: n1-standard-2
disks:
  - name: boot
    type: pd-ssd
    size: 50
    delete_on_termination: true
    mode: READ_WRITE

max_retries: 5
supernet: 10.52.0.0/16
zone:
  - name: us-east1-b
    start: 1
    end: 1
#  - name: us-east4
#    count: 2
#  - name: us-central1
#    count: 3
#  - name: us-west1
#    count: 4
#  - name: northamerica-northeast1
#    count: 5


