ansible_ssh_user: centos
ansible_ssh_public_key_file: ~/.ssh/id_rsa.pub
ansible_ssh_private_key_file: ~/.ssh/id_rsa

project: helium-dc
image: ubuntu-1804
max_retries: 5
supernet: 10.52.0.0/16

mode: server
machine_type: n1-standard-4
preemptible: false
options:
  cephfs:
    name: alpha
    daemon_image: ceph/daemon:latest-luminous
    mon_group_size: 1
    mds_group_size: 1
  nfsv4:
    nfsd_image: heliumdatacommons/nfsd
    mountpoint: /data
    opts: rw,async,fsid=0,insecure,no_subtree_check,anonuid=1000,anongid=1000,no_root_squash
  ganesha:
    mountpoint: /data
  rbd:
    name: alpha
    mon_group_size: 1
    daemon_image: ceph/daemon:latest-luminous
    num_pgs: 8
    unwanted_rbd_features: exclusive-lock object-map fast-diff deep-flatten
    nfsd_image: heliumdatacommons/nfsd
    mountpoint: /data
    opts: rw,async,fsid=0,insecure,no_subtree_check,anonuid=1000,anongid=1000,no_root_squash
  glusterfs:
    version: 4.0
    name: alpha
#    disperse: 4
    replication_factor: 3
    transport_mode: tcp
  gfganesha:
    version: 4.0
    name: alpha
#    disperse: 4
    replication_factor: 3
    transport_mode: tcp

disks:
  - name: boot
    type: pd-ssd
    size: 30
    delete_on_termination: true
    mode: READ_WRITE
  - name: ext-0
    type: pd-ssd
    size: 30
    delete_on_termination: true
    mode: READ_WRITE
zone:
  - name: us-east1-b
    start: 1
    end: 1
#  - name: us-east4
#    count: 2
#  - name: us-central1
#    count: 3
#  - name: us-west1
#    count: 4
#  - name: northamerica-northeast1
#    count: 5


