- hosts: localhost
  gather_facts: false
  roles:
    - create_hosts

- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install Python
      raw: apt-get update && apt-get install -y python

- hosts: server
  gather_facts: false
  become: true
  roles:
    - install_docker

- hosts: client
  gather_facts: false
  become: true
  roles:
    - install_docker
    - install_client_packages

- import_playbook: playbooks/{{ fs }}/main.yml

- hosts: localhost
  tasks:
    - name: Generate benchmark ID
      set_fact:
        benchmark_id: "{{ ansible_date_time.iso8601_micro | to_uuid }}"
      when: mode == 'client'

    - name: Create data directory for the benchmark
      file:
        path: data/{{ benchmark_id }}
        state: directory
        recurse: true
      when: mode == 'client'

    - name: Copy the configuration file
      copy:
        src: group_vars/all.yml
        dest: data/{{ benchmark_id }}/config.yml
      when: mode == 'client'

- hosts: client
  gather_facts: false
  become: true
  roles:
    - download_data