- hosts: localhost
  gather_facts: false
  roles:
    - create_hosts

- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install Python
      raw: apt-get update && apt-get install -y python

- hosts: server
  gather_facts: false
  become: true
  roles:
    - install_docker

- hosts: client
  gather_facts: false
  become: true
  roles:
    - install_docker
    - install_client_packages

- import_playbook: playbooks/{{ fs }}/main.yml

- hosts: client
  gather_facts: false
  become: true
  roles:
    - download_data